#!/usr/bin/env python3
# Description: Loops through json generated by maps2json to build json for charts
# Author: Tyler "-z-" Mulligan

import json, copy, datetime

def main():
    f = open('./data/maps.json') 
    data = f.read()
    maps_json = json.loads(data)['data']

    filesizes = ['bytes']
    mapinfos = 0
    mapshots = 0
    maps = 0
    radars = 0
    waypoints = 0
    licenses = 0
    # this should be generated
    maps_by_year = { 1999: 0, 2000: 0, 2001: 0, 2002: 0, 2003: 0, 2004: 0,
                     2005: 0, 2006: 0, 2007: 0, 2008: 0, 2009: 0, 2010: 0,
                     2011: 0, 2012: 0, 2013: 0, 2014: 0, 2015: 0, 2016: 0 }

    total = 0
    for m in maps_json:
        total += 1
        filesizes.append(m['filesize'])
        dt = datetime.datetime.fromtimestamp(m['date'])
        maps_by_year[dt.year] += 1
        
        if m['mapinfo']:
            mapinfos += 1
        if m['mapshot']:
            mapshots += 1
        if m['map']:
            maps += 1
        if m['radar']:
            radars += 1
        if m['waypoints']:
            waypoints += 1
        if m['license']:
            licenses += 1

    # Pie Charts
    tchart = { 'bindto': '', 'data': { 'columns': [ ['yes'], ['no'] ], 'type': 'pie' } }

    c1 = copy.deepcopy(tchart)
    c1['bindto'] = '#chart-mapinfos'
    c1['data']['columns'][0].append(mapinfos)
    c1['data']['columns'][1].append(total - mapinfos)

    c2 = copy.deepcopy(tchart)
    c2['bindto'] = '#chart-mapshots'
    c2['data']['columns'][0].append(mapshots)
    c2['data']['columns'][1].append(total - mapshots)

    c3 = copy.deepcopy(tchart)
    c3['bindto'] = '#chart-maps'
    c3['data']['columns'][0].append(maps)
    c3['data']['columns'][1].append(total - maps)

    c4 = copy.deepcopy(tchart)
    c4['bindto'] = '#chart-radars'
    c4['data']['columns'][0].append(radars)
    c4['data']['columns'][1].append(total - radars)

    c5 = copy.deepcopy(tchart)
    c5['bindto'] = '#chart-waypoints'
    c5['data']['columns'][0].append(waypoints)
    c5['data']['columns'][1].append(total - waypoints)

    c6 = copy.deepcopy(tchart)
    c6['bindto'] = '#chart-licenses'
    c6['data']['columns'][0].append(licenses)
    c6['data']['columns'][1].append(total - licenses)

    # Scatter Plot
    c7 = { 'bindto': '', 'data': { 'columns': [ ], 'type': 'scatter' } }
    c7['bindto'] = '#chart-filesizes'
    c7['data']['columns'].append(filesizes)

    # Maps over time
    c8 = { 'bindto': '', 'data': { 'x': 'x', 'columns': [ ], 'type': 'line' },
           'axis': { 'x' : { 'type': 'timeseries', 'tick': { 'format': '%Y' } } } }
    c8['bindto'] = '#chart-mapsbyyear'
    c8['data']['columns'].append(['x'] + list(maps_by_year.keys()))
    c8['data']['columns'].append(['maps'] + list(maps_by_year.values()))

    charts = { 
                'mapinfos': c1,
                'mapshots': c2,
                'maps': c3,
                'radars': c4,
                'waypoints': c5,
                'licenses': c6,
                'filesizes': c7,
                'mapsbyyear': c8
             }

    fo = open('data/charts.json', 'w')
    fo.write(json.dumps(charts))
    fo.close()

if __name__ == "__main__":
    main()
