#!/usr/bin/env python3
# Description: Loops through json generated by maps2json to build json for charts
# Author: Tyler "-z-" Mulligan

import json, copy

def main():
    f = open('./data/maps.json') 
    data = f.read()
    maps_json = json.loads(data)['data']

    mapinfos = 0
    mapshots = 0
    maps = 0
    radars = 0
    waypoints = 0
    licenses = 0

    total = 0
    for m in maps_json:
        total += 1
        if m['mapinfo']:
            mapinfos += 1
        if m['mapshot']:
            mapshots += 1
        if m['map']:
            maps += 1
        if m['radar']:
            radars += 1
        if m['waypoints']:
            waypoints += 1
        if m['license']:
            licenses += 1

    tchart = { 'data': { 'columns': [ ['yes'], ['no'] ], 'type': 'pie' } }

    c1 = copy.deepcopy(tchart)
    c1['data']['columns'][0].append(mapinfos)
    c1['data']['columns'][1].append(total - mapinfos)

    c2 = copy.deepcopy(tchart)
    c2['data']['columns'][0].append(mapshots)
    c2['data']['columns'][1].append(total - mapshots)

    c3 = copy.deepcopy(tchart)
    c3['data']['columns'][0].append(maps)
    c3['data']['columns'][1].append(total - maps)

    c4 = copy.deepcopy(tchart)
    c4['data']['columns'][0].append(radars)
    c4['data']['columns'][1].append(total - radars)

    c5 = copy.deepcopy(tchart)
    c5['data']['columns'][0].append(waypoints)
    c5['data']['columns'][1].append(total - waypoints)

    c6 = copy.deepcopy(tchart)
    c6['data']['columns'][0].append(licenses)
    c6['data']['columns'][1].append(total - licenses)

    charts = { 
                'mapinfos': c1,
                'mapshots': c2,
                'maps': c3,
                'radars': c4,
                'waypoints': c5,
                'licenses': c6
             }

    print(json.dumps(charts))
    print(total)

if __name__ == "__main__":
    main()
